#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Non-interactive shells source profile. Interactive shells don't. 
# Gotta fix that
source /etc/profile

# this is my default usermask to give all files 644 perms
umask 022

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
#HISTSIZE=8000
#HISTFILESIZE=16000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
#shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.


# NOTE: Fix this by adding the paths to a set and sourcing from it 
# to avoid double and triple sourcing
# FIXED by using a real path for "me"
me="$HOME/.bash/rc" #change this depending on where your bashrc is

if [ -d ~/.bash ]; then
	for script in ~/.bash/*; do
                if [ $script != $me ]; then
                        source $script #&& echo "$script sourced."
                fi
	done
	unset script
fi

# vim mode
set -o vi



# Only load liquidprompt in interactive shells, not from a script or from scp
# echo $- | grep -q i 2>/dev/null && . /usr/share/liquidprompt/liquidprompt


